/*
Copyright 2018 The kube-fledged Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "k8s.io/kube-fledged/pkg/apis/fledged/v1alpha1"
	scheme "k8s.io/kube-fledged/pkg/client/clientset/versioned/scheme"
)

// ImageCachesGetter has a method to return a ImageCacheInterface.
// A group's client should implement this interface.
type ImageCachesGetter interface {
	ImageCaches(namespace string) ImageCacheInterface
}

// ImageCacheInterface has methods to work with ImageCache resources.
type ImageCacheInterface interface {
	Create(*v1alpha1.ImageCache) (*v1alpha1.ImageCache, error)
	Update(*v1alpha1.ImageCache) (*v1alpha1.ImageCache, error)
	UpdateStatus(*v1alpha1.ImageCache) (*v1alpha1.ImageCache, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ImageCache, error)
	List(opts v1.ListOptions) (*v1alpha1.ImageCacheList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ImageCache, err error)
	ImageCacheExpansion
}

// imageCaches implements ImageCacheInterface
type imageCaches struct {
	client rest.Interface
	ns     string
}

// newImageCaches returns a ImageCaches
func newImageCaches(c *FledgedV1alpha1Client, namespace string) *imageCaches {
	return &imageCaches{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the imageCache, and returns the corresponding imageCache object, and an error if there is any.
func (c *imageCaches) Get(name string, options v1.GetOptions) (result *v1alpha1.ImageCache, err error) {
	result = &v1alpha1.ImageCache{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagecaches").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ImageCaches that match those selectors.
func (c *imageCaches) List(opts v1.ListOptions) (result *v1alpha1.ImageCacheList, err error) {
	result = &v1alpha1.ImageCacheList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagecaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested imageCaches.
func (c *imageCaches) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("imagecaches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a imageCache and creates it.  Returns the server's representation of the imageCache, and an error, if there is any.
func (c *imageCaches) Create(imageCache *v1alpha1.ImageCache) (result *v1alpha1.ImageCache, err error) {
	result = &v1alpha1.ImageCache{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("imagecaches").
		Body(imageCache).
		Do().
		Into(result)
	return
}

// Update takes the representation of a imageCache and updates it. Returns the server's representation of the imageCache, and an error, if there is any.
func (c *imageCaches) Update(imageCache *v1alpha1.ImageCache) (result *v1alpha1.ImageCache, err error) {
	result = &v1alpha1.ImageCache{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("imagecaches").
		Name(imageCache.Name).
		Body(imageCache).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *imageCaches) UpdateStatus(imageCache *v1alpha1.ImageCache) (result *v1alpha1.ImageCache, err error) {
	result = &v1alpha1.ImageCache{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("imagecaches").
		Name(imageCache.Name).
		SubResource("status").
		Body(imageCache).
		Do().
		Into(result)
	return
}

// Delete takes name of the imageCache and deletes it. Returns an error if one occurs.
func (c *imageCaches) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagecaches").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *imageCaches) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagecaches").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched imageCache.
func (c *imageCaches) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ImageCache, err error) {
	result = &v1alpha1.ImageCache{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("imagecaches").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
