/*
Copyright The kube-fledged authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha2

import (
	context "context"

	kubefledgedv1alpha2 "github.com/senthilrch/kube-fledged/pkg/apis/kubefledged/v1alpha2"
	scheme "github.com/senthilrch/kube-fledged/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ImageCachesGetter has a method to return a ImageCacheInterface.
// A group's client should implement this interface.
type ImageCachesGetter interface {
	ImageCaches(namespace string) ImageCacheInterface
}

// ImageCacheInterface has methods to work with ImageCache resources.
type ImageCacheInterface interface {
	Create(ctx context.Context, imageCache *kubefledgedv1alpha2.ImageCache, opts v1.CreateOptions) (*kubefledgedv1alpha2.ImageCache, error)
	Update(ctx context.Context, imageCache *kubefledgedv1alpha2.ImageCache, opts v1.UpdateOptions) (*kubefledgedv1alpha2.ImageCache, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, imageCache *kubefledgedv1alpha2.ImageCache, opts v1.UpdateOptions) (*kubefledgedv1alpha2.ImageCache, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*kubefledgedv1alpha2.ImageCache, error)
	List(ctx context.Context, opts v1.ListOptions) (*kubefledgedv1alpha2.ImageCacheList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *kubefledgedv1alpha2.ImageCache, err error)
	ImageCacheExpansion
}

// imageCaches implements ImageCacheInterface
type imageCaches struct {
	*gentype.ClientWithList[*kubefledgedv1alpha2.ImageCache, *kubefledgedv1alpha2.ImageCacheList]
}

// newImageCaches returns a ImageCaches
func newImageCaches(c *KubefledgedV1alpha2Client, namespace string) *imageCaches {
	return &imageCaches{
		gentype.NewClientWithList[*kubefledgedv1alpha2.ImageCache, *kubefledgedv1alpha2.ImageCacheList](
			"imagecaches",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *kubefledgedv1alpha2.ImageCache { return &kubefledgedv1alpha2.ImageCache{} },
			func() *kubefledgedv1alpha2.ImageCacheList { return &kubefledgedv1alpha2.ImageCacheList{} },
		),
	}
}
