/*
Copyright The kube-fledged authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/senthilrch/kube-fledged/pkg/apis/kubefledged/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeImageCaches implements ImageCacheInterface
type FakeImageCaches struct {
	Fake *FakeFledgedV1alpha1
	ns   string
}

var imagecachesResource = schema.GroupVersionResource{Group: "fledged.k8s.io", Version: "v1alpha1", Resource: "imagecaches"}

var imagecachesKind = schema.GroupVersionKind{Group: "fledged.k8s.io", Version: "v1alpha1", Kind: "ImageCache"}

// Get takes name of the imageCache, and returns the corresponding imageCache object, and an error if there is any.
func (c *FakeImageCaches) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ImageCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(imagecachesResource, c.ns, name), &v1alpha1.ImageCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageCache), err
}

// List takes label and field selectors, and returns the list of ImageCaches that match those selectors.
func (c *FakeImageCaches) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ImageCacheList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(imagecachesResource, imagecachesKind, c.ns, opts), &v1alpha1.ImageCacheList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ImageCacheList{ListMeta: obj.(*v1alpha1.ImageCacheList).ListMeta}
	for _, item := range obj.(*v1alpha1.ImageCacheList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested imageCaches.
func (c *FakeImageCaches) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(imagecachesResource, c.ns, opts))

}

// Create takes the representation of a imageCache and creates it.  Returns the server's representation of the imageCache, and an error, if there is any.
func (c *FakeImageCaches) Create(ctx context.Context, imageCache *v1alpha1.ImageCache, opts v1.CreateOptions) (result *v1alpha1.ImageCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(imagecachesResource, c.ns, imageCache), &v1alpha1.ImageCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageCache), err
}

// Update takes the representation of a imageCache and updates it. Returns the server's representation of the imageCache, and an error, if there is any.
func (c *FakeImageCaches) Update(ctx context.Context, imageCache *v1alpha1.ImageCache, opts v1.UpdateOptions) (result *v1alpha1.ImageCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(imagecachesResource, c.ns, imageCache), &v1alpha1.ImageCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageCache), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeImageCaches) UpdateStatus(ctx context.Context, imageCache *v1alpha1.ImageCache, opts v1.UpdateOptions) (*v1alpha1.ImageCache, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(imagecachesResource, "status", c.ns, imageCache), &v1alpha1.ImageCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageCache), err
}

// Delete takes name of the imageCache and deletes it. Returns an error if one occurs.
func (c *FakeImageCaches) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(imagecachesResource, c.ns, name), &v1alpha1.ImageCache{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeImageCaches) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(imagecachesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ImageCacheList{})
	return err
}

// Patch applies the patch and returns the patched imageCache.
func (c *FakeImageCaches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ImageCache, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(imagecachesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ImageCache{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageCache), err
}
